### ISSUE TITLE
How to send sensor data to pc with USB plug

### ISSUE THREAD

**Issue by devsteppe9** [ahmadfarisfs/infrahead#1]
Hello @ahmadfarisfs 
I am trying to send sensor Data to local machine (PC). Is there any way to send sensor data to PC without using bluetooth, wifi modules. If you have any suggestion please give your opinion

**Comment by ahmadfarisfs** [comment]
Hello, sorry for the inactivity, to send data to your pc using Bluetooth you can use BLE, or maybe use the popular ESP32 or ESP8266 as an AP and access the data from there, or just a plain serial output from the micro controller to PC.
